version: "3.8"
services:
  abbott-bots:
    image: ghcr.io/adamlearns/abbott-bots:latest
    restart: unless-stopped
    env_file: .env.production.local

    depends_on:
      - db
    volumes:
      # This could be replaced with an external volume so that it's not
      # hard-coded to $HOME/database_backups.
      # See https://docs.docker.com/storage/volumes/#use-a-volume-with-docker-compose
      - $HOME/database_backups:/database_backups
  abbott-web:
    image: adamlearns/abbott-web:latest
    restart: unless-stopped
    env_file:
      - ./packages/web/.env.production.local
    depends_on:
      - db
    ports:
      - 3000:3000
  db:
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bar
      POSTGRES_DB: foo

    volumes:
      - $HOME/tmp/postgres:/var/lib/postgresql/data
    ports:
      # This is only for connections from outside of this compose file
      - 5432:5432
