version: "3.8"
services:
  abbott-bots:
    image: ghcr.io/adamlearns/abbott-bots:latest
    restart: unless-stopped
    env_file: packages/bots/.env.production.local
    depends_on:
      db:
        condition: service_healthy
    volumes:
      # This could be replaced with an external volume so that it's not
      # hard-coded to $HOME/database_backups.
      # See https://docs.docker.com/storage/volumes/#use-a-volume-with-docker-compose
      - $HOME/database_backups:/database_backups
    ports:
      - 3001:3001
  abbott-web:
    image: ghcr.io/adamlearns/abbott-web:latest
    restart: unless-stopped
    env_file:
      - ./packages/web/.env.production.local
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 3000:3000
  db:
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bar
      POSTGRES_DB: foo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - $HOME/tmp/postgres:/var/lib/postgresql/data
    ports:
      # This is only for connections from outside of this compose file
      - 5432:5432
