# This file really SHOULDN'T exist, but I keep finding myself wanting to test
# the Docker image that I create, and the image/env_file/volumes need to change.
# This file has the required changes.
version: "3.8"
services:
  abbott-bots:
    image: adamlearns/abbott-bots:latest
    restart: unless-stopped
    env_file:
      - ./packages/bots/.env.development.local

      # This is to specify a different database connection string (so that we
      # connect to the one from this compose file)
      - ./packages/bots/.env.development-docker.local

    depends_on:
      db:
        condition: service_healthy
    volumes:
      # This could be replaced with an external volume so that it's not
      # hard-coded to $HOME/database_backups.
      # See https://docs.docker.com/storage/volumes/#use-a-volume-with-docker-compose
      - $HOME/tmp/abbott_database_backups:/Users/adam/tmp/abbott_database_backups
  abbott-web:
    image: adamlearns/abbott-web:latest
    restart: unless-stopped
    env_file:
      - ./packages/web/.env.development.local

      # (see the comment above for the bot image for why this is needed)
      - ./packages/web/.env.development-docker.local
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 3000:3000
  db:
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bar
      POSTGRES_DB: foo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - dbvolume:/var/lib/postgresql/data
    ports:
      # This is only for connections from outside of this compose file
      - 5434:5432
volumes:
  dbvolume:
