version: '3.8'
services:
  db:
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bar
      POSTGRES_DB: foo
    volumes:
      - $HOME/tmp/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
