- name: Set up for Abbott
  hosts: minipc
  become: yes
  tasks:
    - name: Install packages
      ansible.builtin.package:
        name:
          - sudo
          - btop
          - htop
          - screen
          - curl
          - git
          - vim
          - unzip
          - build-essential
          - pgcli
          - bat # this is installed as "batcat"
          - ripgrep
          - lsd
        state: present
    - name: Check out the Abbott code
      ansible.builtin.git:
        repo: "https://github.com/AdamLearns/Abbott.git"
        dest: ~/code/Abbott
      become: no

    - name: Set up Docker
      ansible.builtin.include_tasks:
        file: docker.yaml

    # Run "docker-compose up". We don't do this using a
    # community.docker.docker_compose task because we run into a bunch of Python
    # errors that are hard to fix.
    - name: Run PostgreSQL in a container
      ansible.builtin.command: docker-compose up -d
      become: no
      args:
        chdir: ~/code/Abbott/src/database/

    - name: Run Watchtower
      docker_container:
        name: watchtower
        image: containrrr/watchtower
        restart_policy: unless-stopped
        env:
          # Check for a new image every 60 seconds
          WATCHTOWER_POLL_INTERVAL: "60"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock

    - name: Run Abbott
      ansible.builtin.command: docker-compose up -d
      become: no
      args:
        chdir: ~/code/Abbott/
