name: Docker Image CI

on:
  push:
    branches: [$default-branch]

  # Allow manual triggering
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      # Read/write access to the repository. Write access is needed only for
      # workflow_dispatch.
      contents: write
      # Allow access to the GitHub container registry
      packages: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Retrieve date in seconds
        run: |
          echo "VALUE=$(date +%s)" >> $GITHUB_OUTPUT
        id: date_in_seconds

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5.1.0
        with:
          file: ./Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.date_in_seconds.outputs.VALUE }}
